### PR TITLE
Creation of higher level data repository

### PR DESCRIPTION
**Pull request by loicrouchon**
- Moving data logic in a data repository layer
- No direct dependency on Panache except in the data layer
- No need for spy in the unit tests (separation between Quarkus Panache augmented code and manually written one)

### CODE REVIEW

**Comment by fabricepipart** [comment]
Whatch out I think you need to rebase your branch. For example, the exception type are out of date

**Comment by fabricepipart** [comment]
It looks a "bit complicated" but Smart. I think I like it

**Comment by loicrouchon** [comment]
> Whatch out I think you need to rebase your branch. For example, the exception type are out of date

This PR is up to date with latest commits available on branch https://github.com/loicrouchon/teknichrono/commits/feature/quarkus-migration (which is the merge of PR9 in commit https://github.com/loicrouchon/teknichrono/commit/241aae2b3d20144865c53171433c4e8b37473c4f )

Are you sure you pushed everything or did I miss something?

**Comment by fabricepipart** [comment]
I can't find what I saw at the moment... Maybe I was just tired... Anyway, it's fine now

**Pull request merged**
